# This is a basic workflow to help you get started with Actions

name: Docker Image for GitLab

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  get_octo_cli_version:
    runs-on: windows-latest
    outputs: 
      VERSION: ${{ steps.choco.outputs.VERSION }}
      CONTINUE: ${{ steps.choco.outputs.CONTINUE }}
    steps:
      - uses: actions/checkout@v2
      - id: choco
        name: Compare latest version with container
        run:
          $chocoInformationRaw = choco info octopustools --limitoutput
          $version = ($chocoInformationRaw.Split("|"))[1]
          $versionSplit = $version.Split(".")
          
          $response = try {
            $repositoryTags = Invoke-RestMethod "https://registry.hub.docker.com/v1/repositories/octopuslabs/gitlab-octocli/tags"
          } catch [System.Net.WebException] { 
            $_.Exception.Response 
          }
          
          echo "::set-output name=VERSION::$version"
          
          if ($null -eq $response)
          {
            $matchingTag = $repositoryTags | Where-Object {$_.Name -eq $version}
            
            if ($null -ne $matchingTag)
            {
              Write-Host "Docker container already has latest version."
              echo "::set-output name=Continue::No"
            }
            else
            {
              Write-Host "Octopus CLI has been updated, create new image."
              echo "::set-output name=Continue::Yes"
            }
          }
          else
          {
            if (response.StatusCode.value__ -eq 404)
            {
              Write-Host "No tags exist for repo, assuming first build."
              echo "::set-output name=CONTINUE::Yes"
            }
          }
          
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
